### ISSUE TITLE
Add model tests

### ISSUE THREAD

**Issue by jhsu802701** [OpenTwinCities/adopt-a-tree#28]

**Comment by wbushey** [comment]
Adopt A Tree actually has a few bit of unit test coverage for models in [spec/models](https://github.com/OpenTwinCities/adopt-a-tree/tree/master/spec/models). You can run these tests by executing either `rspec` or `rake`.

You'll see that there are some pending tests related to PromoCodes and PromoVendors. That code is never actually used (it's part of a feature we started developing that was eventually dropped); so it might be better to remove those models and pending specs.

Given that there is existing model test coverage, do you want to close this? Or, do you want to further define what success for this ticket looks like?
