### ISSUE TITLE
Failures and warnings the first time I run tests but not the second time

### ISSUE THREAD

**Issue by jhsu802701** [OpenTwinCities/adopt-a-tree#42]
When I run the build_fast.sh script (in the build_fast branch) in my Docker container (using the rbenv-adoptatree image), there are failures and warnings I get the first time I run this script but not the second time.

I get the following Google Maps API warning during the Adoption Form:
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
Google Maps API warning: InvalidKey https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key

I get the following failure/error:
    Failure/Error: expect(page).to have_selector '#adoption_form'      [22/505]
       expected to find css "#adoption_form" but there were no matches
     # ./spec/features/adoption_form_spec.rb:30:in `block (3 levels) in <top (required)>'

**Comment by wbushey** [comment]
Regarding the Google Maps Warnings, I don't think those are a problem, as they are simply warnings. The tests should still function despite those warnings; Google will still deliver Google Maps to the test. That said, if those do turn out to be an issue, you can [grab a Google Maps API key](https://developers.google.com/maps/documentation/javascript/get-api-key) and set it using the [environment variable `GOOGLE_MAPS_API_KEY`](https://github.com/OpenTwinCities/adopt-a-tree/blob/master/config/config.yml#L15).

As for the Feature failure, is it consistent in failing the first time and passing the second time?

**Comment by jhsu802701** [comment]
I was able to resolve this issue by extending the Capybara wait time for the failing tests.  My home desktop computer is a rather old and slow one, and that meant that the Adopt form was slow enough to affect the tests.  (Capybara's default wait time is only 2 seconds.)  The tests didn't fail on my newer MacBook Air or in Travis CI.
