### ISSUE TITLE
RuboCop

### ISSUE THREAD

**Issue by jhsu802701** [OpenTwinCities/adopt-a-tree#45]
I see that the .travis.yml file includes a command for running RuboCop, but the rubocop gem is not in Gemfile.lock.  Is there any particular reason for running RuboCop in Travis CI but not in the development environment?  If there isn't, then I will add RuboCop to the Gemfile so we can run it locally and make sure that we have corrected (or suppressed) any offenses found.

**Comment by wbushey** [comment]
As far as I know, no, there is no reason why we don't have RuboCop running in development. Feel free to add it to the Gemfile,

**Comment by jhsu802701** [comment]
There are 274 offenses.  I'll get to this later.
