### ISSUE TITLE
Tree tool tips should display something besides Thing ID

### ISSUE THREAD

**Issue by wbushey** [OpenTwinCities/adopt-a-tree#75]
Currently, if a user places their mouse over a tree, a tool tip will appear that displays the Thing ID for that tree. This is a pretty cryptic and unuseful piece of information to provide the user.

Instead of displaying the Thing ID in the tool tip, one of the following could be displayed:
 * the species of the tree
 * the adoption status
 * nothing (no tool tip at all)

**Comment by jhsu802701** [comment]
FOR REFERENCE:
I believe that this is controlled in app/assets/javascripts/main.js.erb -> function addMarkersAround -> success: function -> thingTitle (var thingTitle = thingType + '_' + thing.id;).

**Comment by jhsu802701** [comment]
I pushed a solution (eliminating the tool tip) to the 2017_05_23 branch, which I have submitted in a pull request.
