### ISSUE TITLE
Fill in pending tests

### ISSUE THREAD

**Issue by jhsu802701** [OpenTwinCities/adopt-a-tree#91]
1) PromoCodesHelper add some examples to (or delete) /home/winner/shared/adopt
-a-tree/spec/helpers/promo_codes_helper_spec.rb                                                         
                                                                                
  2) PromoCode add some examples to (or delete) /home/winner/shared/adopt-a-tree
/spec/models/promo_code_spec.rb                                                                                 

  3) PromoVendor add some examples to (or delete) /home/winner/shared/adopt-a-tr
ee/spec/models/promo_vendor_spec.rb

**Comment by jhsu802701** [comment]
Promo codes helper not yet implemented

**Comment by wbushey** [comment]
This is definitely a good thing to address. We've had a long standing issue about removing the Promo classes (#43). I think rather than putting in the effort to write tests for code that isn't used, it would be best to simply delete that code so we no longer need to maintain it.
